nomenclature:
  name: faculty_profile
  verboseName: FacApp
description: Create your official profile page
baseUrls:
  http: faculty_profile/
  ws: faculty_profile/
  static: faculty_profile/
acceptables:
  ipAddressRings:
    - internet
    - intranet
    - maintainers
    - specifics
    - administrator
    - self
  roles:
    - name: FacultyMember
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
isApi: true
