nomenclature:
  name: faculty_profile
  verboseName: FacultyProfile
baseUrls:
  http: faculty_profile/
  ws: faculty_profile/
acceptables:
  roles:
    - name: FacultyMember
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
isApi: true
